version: "3"
services:
  app:
    build: .
    tty: true
    command: node /app/index.js "/input/資組.zip"
    volumes: 
      - ./app:/app/
      - ./cache:/cache/
      - ./example folder:/input/
      #- ./example folder:/input/
      #- ./example folder:/output/